### ISSUE TITLE
>> Compilation failure

### ISSUE THREAD

**Issue by skxo** [RoSchmi/Beaglebone-PRU-RPMsg-HelloWorld#1]
Hi Ron,

I am working on Pocket beagle with version Linux beaglebone 4.4.91-ti-r133 #1 SMP Tue Oct 10 05:18:08 UTC 2017 armv7l GNU/Linux.
After cloning your repo, I launch sudo make install -B and I obtained:
/usr/bin/clpru -v3 -O2 --endian=little --hardware_mac=on --include_path=/usr/include/arm-linux-gnueabihf/ --include_path=/usr/lib/ti/pru-software-support-package/include/ --include_path=/usr/lib/ti/pru-software-support-package/include/am335x/ --include_path=/usr/share/ti/cgt-pru/include/ -ppd -ppa -fe /home/debian/hello/pru0//main0.object /home/debian/hello/main0.c -D PRU0
"/tmp/TI0x8K980px", ERROR!   at EOF: [E1500] file access error:  failed to open
                                             "/home/debian/hello/pru0//main0.object"
                                             for writing
"/tmp/TI0x8K980px", ERROR!  : [E1000] Failed to write object file :
                                      /home/debian/hello/pru0//main0.object

>> Compilation failure
Makefile:22: recipe for target 'am335x-pru0-fw' failed
make: *** [am335x-pru0-fw] Error 1

Do you have an idea? I am newbie on TI chip and particularly PRU.
Thanks for all.
sk

**Comment by RoSchmi** [comment]
Hi, thanks for your interest. I'll have a look later today. Can it be that you didn't install in exactly the named directory path? Please give me a feedback I you found the reason by yourself.
Kind Regards Roland

**Comment by RoSchmi** [comment]
the content of the repository must be in the folder 
/home/debian/PruProgs/Pru_RPMsg_Hello

in this folder then the files hello, hello.c, hello.cmd etc. must to be found

**Comment by skxo** [comment]
Hi ro,

I modified the CODE_ROOT variable ofc.
i fixed my problem.
I had to create the folder pru0 and pru1.
So mkdir pru0;mkdir pru1. 

Thanks for all!
sk
